import * as anchor from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
const conn = new Connection("http://127.0.0.1:8899", "confirmed");
const admin = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(readFileSync(`${homedir()}/.config/solana/id.json`, "utf8"))));
const idl = JSON.parse(readFileSync(new URL("../../target/idl/floorlaunch.json", import.meta.url).pathname, "utf8"));
idl.address = "QsixfrupxfVEDDYuQsR4vJcE58bbNfctD9WjijM9BjM";
const program = new anchor.Program(idl, new anchor.AnchorProvider(conn, new anchor.Wallet(admin), {}));
const m: any = await (program.account as any).market.fetch(new PublicKey("HEvnWHuKBznoLehG3ymJM9k7sfNjcAyU36zt8GmiriG1"));
const now = Math.floor(Date.now()/1000);
console.log("on-chain indexLastTs age:", now - Number(m.indexLastTs), "s");
console.log("on-chain slot-clock check via blocktime...");
const slot = await conn.getSlot();
const bt = await conn.getBlockTime(slot);
console.log("validator clock vs wall:", now - (bt ?? 0), "s behind");
